### BUTTONS AND LEVERS ###

## site-specific details ##
name: PC Electrical & Solar
slogan: Power to the People
phone: 0402-256-641
email: peter@pcelectricalandsolar.com.au
abn: "42 523 060 327"
url: http://www.pcelectricalandsolar.com.au
description: Electricians servicing Melbourne. For all domestic and commercial electrical and solar installations and repairs.

## Design credits ##
designer: D. Allen
designerUrl: http://syntheta.se

## Resources ##
#fonts
fontawesome: https://use.fontawesome.com/0523816ffe.js
fonts: Open+Sans|Days+One|Satisfy
#jQuery
jquery: https://code.jquery.com/jquery-1.11.0.min.js
#background image
background: /resources/img/solar-panel.jpg


## layout ##
max-width: 1024
primary-colour: "#142553"
#text area background colour
textbg: "rgba(255,255,255,0.8)"

## jekyll control ##
markdown: kramdown
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
